{{- if not .Values.database.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unifi.mongoUserSecret" . }}
type: Opaque
data:
  username: {{ .Values.database.username | default "unifi" |  b64enc }}
  password: {{ .Values.database.password | default (randAlphaNum 10) | b64enc }}
{{- end }}
